image: centos:8

stages:
        - build

compile:
        stage: build
        tags:
                - docker
        script:
                - curl -L https://raw.githubusercontent.com/netmax79/XenOrchestra-Installer-Centos8/master/XOA-Installer-Centos8.sh | sh

